import { ROLES } from "./roles.js";
import { PERMISSIONS } from "./permissions.js";

export const rolePermissions = {
  [ROLES.ADMIN]: [
    // PERMISSIONS.VIEW_ALL_COMPLAINTS,
    // PERMISSIONS.ASSIGN_COMPLAINT,
    // PERMISSIONS.CLOSE_COMPLAINT
    ...Object.values(PERMISSIONS) // 🔥 FULL POWER
  ],

  [ROLES.OFFICER]: [
    PERMISSIONS.VIEW_ALL_OFFICERS,
    PERMISSIONS.VIEW_ALL_COMPLAINTS,
    PERMISSIONS.VIEW_ASSIGNED_COMPLAINTS,
    PERMISSIONS.UPDATE_COMPLAINT_STATUS,
    PERMISSIONS.ADD_OFFICER_REMARK,
    PERMISSIONS.REQUEST_MORE_INFO,
    PERMISSIONS.UPLOAD_ACTION_PROOF,
    PERMISSIONS.CLOSE_COMPLAINT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.UPDATE_OFFICER_DEPARTMENT
  ],

  [ROLES.CITIZEN]: [
    PERMISSIONS.CREATE_COMPLAINT,
    PERMISSIONS.VIEW_OWN_COMPLAINT,
    PERMISSIONS.EDIT_OWN_COMPLAINT,
    PERMISSIONS.DELETE_OWN_COMPLAINT,
    PERMISSIONS.ADD_COMPLAINT_COMMENT,
    PERMISSIONS.UPLOAD_COMPLAINT_PROOF
  ]
};
